
# Dotfiles Manifest
# Format: [file_entry.name]
#         operation = "operation_type"
#         destination = "path_relative_to_home"

[".vimrc"]
operation = "symlink"
destination = ""  # Empty means directly in $HOME

[".config/helix/config.toml"]
operation = "symlink"
destination = ".config/helix"
